services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: bitnova-backend:dev
    container_name: bitnova-backend
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./app:/app/app

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started


  ethereum-deposit-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app  
    image: bitnova-backend:dev
    container_name: bitnova-ethereum-deposit-monitor
    restart: unless-stopped

    env_file:
      - .env

    command: ["python", "-m", "app.services.ethereum_deposit_monitor"]

    depends_on:
      postgres:
        condition: service_healthy

  ethereum-withdrawal-broadcaster:
    build:
      context: .
      dockerfile: Dockerfile
    image: bitnova-backend:dev
    container_name: bitnova-ethereum-withdrawal-broadcaster
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./app:/app/app

    command: ["python", "-m", "app.services.ethereum_withdrawal_broadcaster"]

    depends_on:
      postgres:
        condition: service_healthy

  ethereum-withdrawal-confirmation-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: bitnova-backend:dev
    container_name: bitnova-ethereum-withdrawal-confirmation-monitor
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./app:/app/app

    command: ["python", "-m", "app.services.ethereum_withdrawal_confirmation_monitor"]

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: bitnova-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: bitnova
      POSTGRES_USER: bitnova
      POSTGRES_PASSWORD: bitnova_password

    ports:
      - "5440:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U bitnova -d bitnova"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: bitnova-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command:
      - redis-server
      - --appendonly
      - "yes"


volumes:
  postgres_data:
  redis_data:
