services:

  postgres:
    image: postgres:17
    container_name: bitnova-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: bitnova
      POSTGRES_USER: bitnova
      POSTGRES_PASSWORD: bitnova_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U bitnova -d bitnova"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: bitnova-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command:
      - redis-server
      - --appendonly
      - "yes"


volumes:
  postgres_data:
  redis_data: