"""add withdrawals

Revision ID: 4564185a6bfd
Revises: 7252705eb5f6
Create Date: 2026-08-14 07:14:49.348832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4564185a6bfd'
down_revision: Union[str, Sequence[str], None] = '7252705eb5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(length=30), nullable=False),
    sa.Column('destination_address', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('ledger_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['ledger_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_withdrawal_user_idempotency_key')
    )
    op.create_index(op.f('ix_withdrawals_account_id'), 'withdrawals', ['account_id'], unique=False)
    op.create_index(op.f('ix_withdrawals_asset_id'), 'withdrawals', ['asset_id'], unique=False)
    op.create_index(op.f('ix_withdrawals_ledger_transaction_id'), 'withdrawals', ['ledger_transaction_id'], unique=False)
    op.create_index(op.f('ix_withdrawals_network'), 'withdrawals', ['network'], unique=False)
    op.create_index(op.f('ix_withdrawals_status'), 'withdrawals', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawals_user_id'), 'withdrawals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawals_user_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_status'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_network'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_ledger_transaction_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_asset_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_account_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    # ### end Alembic commands ###