"""add deposits

Revision ID: 7252705eb5f6
Revises: eca6531ff399
Create Date: 2026-08-14 03:50:50.119569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7252705eb5f6'
down_revision: Union[str, Sequence[str], None] = 'eca6531ff399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_address_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(length=30), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ledger_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['ledger_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_address_id'], ['wallet_addresses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network', 'blockchain_tx_hash', name='uq_deposit_network_tx_hash')
    )
    op.create_index(op.f('ix_deposits_asset_id'), 'deposits', ['asset_id'], unique=False)
    op.create_index(op.f('ix_deposits_ledger_transaction_id'), 'deposits', ['ledger_transaction_id'], unique=False)
    op.create_index(op.f('ix_deposits_network'), 'deposits', ['network'], unique=False)
    op.create_index(op.f('ix_deposits_status'), 'deposits', ['status'], unique=False)
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_index(op.f('ix_deposits_wallet_address_id'), 'deposits', ['wallet_address_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deposits_wallet_address_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_status'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_network'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_ledger_transaction_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_asset_id'), table_name='deposits')
    op.drop_table('deposits')
    # ### end Alembic commands ###