"""add idempotency transaction reference

Revision ID: e53ae44f3d72
Revises: 37d0974f3bdc
Create Date: 2026-08-11 02:01:32.050492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53ae44f3d72'
down_revision: Union[str, Sequence[str], None] = '37d0974f3bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_records', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.add_column('idempotency_records', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'idempotency_records', 'ledger_transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'idempotency_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idempotency_records', type_='foreignkey')
    op.drop_constraint(None, 'idempotency_records', type_='foreignkey')
    op.drop_column('idempotency_records', 'status')
    op.drop_column('idempotency_records', 'transaction_id')
    # ### end Alembic commands ###