"""add wallet addresses

Revision ID: eca6531ff399
Revises: 59e0499f0cbc
Create Date: 2026-08-14 01:33:37.006759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca6531ff399'
down_revision: Union[str, Sequence[str], None] = '59e0499f0cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('address_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network', 'address', name='uq_wallet_address_network_address'),
    sa.UniqueConstraint('wallet_id', 'asset_id', 'network', name='uq_wallet_address_asset_network')
    )
    op.create_index(op.f('ix_wallet_addresses_asset_id'), 'wallet_addresses', ['asset_id'], unique=False)
    op.create_index(op.f('ix_wallet_addresses_status'), 'wallet_addresses', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_addresses_wallet_id'), 'wallet_addresses', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_addresses_wallet_id'), table_name='wallet_addresses')
    op.drop_index(op.f('ix_wallet_addresses_status'), table_name='wallet_addresses')
    op.drop_index(op.f('ix_wallet_addresses_asset_id'), table_name='wallet_addresses')
    op.drop_table('wallet_addresses')
    # ### end Alembic commands ###