"""create email otp table

Revision ID: efaa9402a90f
Revises: 3d434d15ebe8
Create Date: 2026-09-07 22:46:41.247154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'efaa9402a90f'
down_revision: Union[str, Sequence[str], None] = '3d434d15ebe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_index(op.f('ix_email_otps_user_id'), 'email_otps', ['user_id'], unique=False)
    op.drop_index(op.f('ix_kyc_records_status'), table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_user_id'), table_name='kyc_records')
    op.drop_table('kyc_records')
    op.drop_constraint(op.f('admin_permissions_name_key'), 'admin_permissions', type_='unique')
    op.drop_index(op.f('ix_admin_permissions_name'), table_name='admin_permissions')
    op.create_index(op.f('ix_admin_permissions_name'), 'admin_permissions', ['name'], unique=True)
    op.drop_constraint(op.f('admin_roles_name_key'), 'admin_roles', type_='unique')
    op.drop_index(op.f('ix_admin_roles_name'), table_name='admin_roles')
    op.create_index(op.f('ix_admin_roles_name'), 'admin_roles', ['name'], unique=True)
    op.drop_constraint(op.f('admin_users_email_key'), 'admin_users', type_='unique')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # op.alter_column('bank_accounts', 'account_holder_name',
    #            existing_type=sa.VARCHAR(length=150),
    #            type_=sa.String(length=255),
    #            existing_nullable=False)
    # op.alter_column('bank_accounts', 'bank_name',
    #            existing_type=sa.VARCHAR(length=150),
    #            type_=sa.String(length=255),
    #            existing_nullable=False)
    # op.alter_column('bank_accounts', 'account_type',
    #            existing_type=sa.VARCHAR(length=30),
    #            type_=sa.Enum('SAVINGS', 'CURRENT', name='bankaccounttype'),
    #            nullable=False)
    # op.alter_column('bank_accounts', 'status',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'DISABLED', name='bankaccountstatus'),
    #            existing_nullable=False)
    # op.create_unique_constraint('uq_user_bank_account', 'bank_accounts', ['user_id', 'account_number', 'ifsc_code'])
    # op.drop_column('bank_accounts', 'is_verified')
    op.alter_column('deposits', 'wallet_address_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('deposits', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_deposits_blockchain_log_index'), table_name='deposits')
    op.drop_constraint(op.f('uq_deposit_network_tx_hash'), 'deposits', type_='unique')
    op.drop_index(op.f('ix_deposits_wallet_address_id'), table_name='deposits')
    op.create_index(op.f('ix_deposits_wallet_address_id'), 'deposits', ['wallet_address_id'], unique=False)
    op.drop_index(op.f('uq_deposit_network_tx_log'), table_name='deposits')
    op.create_unique_constraint('uq_deposit_network_tx_log', 'deposits', ['network', 'blockchain_tx_hash', 'blockchain_log_index'])
    op.drop_column('deposits', 'account_id')
    op.drop_index(op.f('ix_fiat_deposits_created_at'), table_name='fiat_deposits')
    op.drop_index(op.f('ix_fiat_deposits_user_status'), table_name='fiat_deposits')
    op.drop_constraint(op.f('fiat_deposits_approved_by_admin_id_fkey'), 'fiat_deposits', type_='foreignkey')
    op.create_foreign_key(None, 'fiat_deposits', 'admin_users', ['approved_by_admin_id'], ['id'])
    # op.alter_column('ledger_transactions', 'user_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    op.create_unique_constraint(None, 'payment_orders', ['payment_session_id'])
    # op.alter_column('trades', 'buyer_user_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('trades', 'seller_user_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    op.drop_constraint(op.f('fk_trades_buyer_user_id'), 'trades', type_='foreignkey')
    op.drop_constraint(op.f('fk_trades_seller_user_id'), 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'users', ['buyer_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'trades', 'users', ['seller_user_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('wallet_addresses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('withdrawals', 'rejection_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('idx_withdrawals_status'), table_name='withdrawals')
    op.drop_index(op.f('uq_withdrawals_blockchain_tx_hash'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_blockchain_tx_hash'), table_name='withdrawals')
    op.create_index(op.f('ix_withdrawals_blockchain_tx_hash'), 'withdrawals', ['blockchain_tx_hash'], unique=True)
    op.create_index(op.f('ix_withdrawals_approved_by_admin_id'), 'withdrawals', ['approved_by_admin_id'], unique=False)
    op.create_foreign_key(None, 'withdrawals', 'admin_users', ['approved_by_admin_id'], ['id'], ondelete='SET NULL')
    op.drop_column('withdrawals', 'provider')
    op.drop_column('withdrawals', 'utr_number')
    op.drop_column('withdrawals', 'provider_reference')
    op.drop_column('withdrawals', 'bank_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('bank_account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('withdrawals', sa.Column('provider_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('withdrawals', sa.Column('utr_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('withdrawals', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.drop_index(op.f('ix_withdrawals_approved_by_admin_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_blockchain_tx_hash'), table_name='withdrawals')
    op.create_index(op.f('ix_withdrawals_blockchain_tx_hash'), 'withdrawals', ['blockchain_tx_hash'], unique=False)
    op.create_index(op.f('uq_withdrawals_blockchain_tx_hash'), 'withdrawals', ['blockchain_tx_hash'], unique=True)
    op.create_index(op.f('idx_withdrawals_status'), 'withdrawals', ['status'], unique=False)
    op.alter_column('withdrawals', 'rejection_reason',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('wallet_addresses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key(op.f('fk_trades_seller_user_id'), 'trades', 'users', ['seller_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_trades_buyer_user_id'), 'trades', 'users', ['buyer_user_id'], ['id'], ondelete='SET NULL')
    # op.alter_column('trades', 'seller_user_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # op.alter_column('trades', 'buyer_user_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    op.drop_constraint(None, 'payment_orders', type_='unique')
    # op.alter_column('ledger_transactions', 'user_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    op.drop_constraint(None, 'fiat_deposits', type_='foreignkey')
    op.create_foreign_key(op.f('fiat_deposits_approved_by_admin_id_fkey'), 'fiat_deposits', 'admin_users', ['approved_by_admin_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_fiat_deposits_user_status'), 'fiat_deposits', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_fiat_deposits_created_at'), 'fiat_deposits', ['created_at'], unique=False)
    op.add_column('deposits', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_deposit_network_tx_log', 'deposits', type_='unique')
    op.create_index(op.f('uq_deposit_network_tx_log'), 'deposits', ['network', 'blockchain_tx_hash', 'blockchain_log_index'], unique=True)
    op.drop_index(op.f('ix_deposits_wallet_address_id'), table_name='deposits')
    op.create_index(op.f('ix_deposits_wallet_address_id'), 'deposits', ['account_id'], unique=False)
    op.create_unique_constraint(op.f('uq_deposit_network_tx_hash'), 'deposits', ['network', 'blockchain_tx_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_deposits_blockchain_log_index'), 'deposits', ['blockchain_log_index'], unique=False)
    op.alter_column('deposits', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('deposits', 'wallet_address_id',
               existing_type=sa.UUID(),
               nullable=True)
    # op.add_column('bank_accounts', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # op.drop_constraint('uq_user_bank_account', 'bank_accounts', type_='unique')
    # op.alter_column('bank_accounts', 'status',
            #    existing_type=sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'DISABLED', name='bankaccountstatus'),
            #    type_=sa.VARCHAR(length=20),
            #    existing_nullable=False)
    # op.alter_column('bank_accounts', 'account_type',
            #    existing_type=sa.Enum('SAVINGS', 'CURRENT', name='bankaccounttype'),
            #    type_=sa.VARCHAR(length=30),
            #    nullable=True)
    # op.alter_column('bank_accounts', 'bank_name',
            #    existing_type=sa.String(length=255),
            #    type_=sa.VARCHAR(length=150),
            #    existing_nullable=False)
    # op.alter_column('bank_accounts', 'account_holder_name',
            #    existing_type=sa.String(length=255),
            #    type_=sa.VARCHAR(length=150),
            #    existing_nullable=False)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('admin_users_email_key'), 'admin_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_admin_roles_name'), table_name='admin_roles')
    op.create_index(op.f('ix_admin_roles_name'), 'admin_roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('admin_roles_name_key'), 'admin_roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_admin_permissions_name'), table_name='admin_permissions')
    op.create_index(op.f('ix_admin_permissions_name'), 'admin_permissions', ['name'], unique=False)
    op.create_unique_constraint(op.f('admin_permissions_name_key'), 'admin_permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.create_table('kyc_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('document_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_by_admin_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admin_users.id'], name=op.f('kyc_records_reviewed_by_admin_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('kyc_records_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('kyc_records_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('kyc_records_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_kyc_records_user_id'), 'kyc_records', ['user_id'], unique=True)
    op.create_index(op.f('ix_kyc_records_status'), 'kyc_records', ['status'], unique=False)
    op.drop_index(op.f('ix_email_otps_user_id'), table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    # ### end Alembic commands ###